weights = {
    'ABS': 19,
    'ASR (traction control)': 58,
    'AUX socket': 64,
    'Active cruise control': 39,
    'Adjustable suspension': 23,
    'Aftermarket radio': 18,
    'Air curtains': 58,
    'Airbag protecting the knees': 41,
    'Alarm': 66,
    'Alloy wheels': 92,
    'Automatic air conditioning': 62,
    'Auxiliary heating': 15,
    'Blind spot sensor': 33,
    'Bluetooth': 62,
    'CD': 100,
    'CD changer': 22,
    'Central locking': 19,
    'Cruise control': 59,
    'DVD player': 33,
    'Daytime running lights': 69,
    'Drivers airbag': 25,
    'Dual zone air conditioning': 66,
    'ESP(stabilization of the track)': 54,
    'Electric front windows': 25,
    'Electric rear windows': 67,
    'Electrically adjustable mirrors': 34,
    'Electrically adjustable seats': 41,
    'Electrochromic rear view mirror': 46,
    'Electrochromic side mirrors': 49,
    'Factory radio': 42,
    'Fog lights': 61,
    'Four-zone air conditioning': 15,
    'Front parking sensors': 79,
    'Front side airbags': 62,
    'GPS navigation': 71,
    'HUD(head-up display)': 12,
    'Heated front seats': 87,
    'Heated rear seats': 16,
    'Heated side mirrors': 66,
    'Heated windscreen': 37,
    'Hook': 43,
    'Immobilizer': 40,
    'Isofix': 65,
    'LED lights': 69,
    'Lane assistant': 36,
    'Leather upholstery': 71,
    'MP3': 62,
    'Manual air conditioning': 71,
    'Multifunction steering wheel': 53,
    'On-board computer': 46,
    'Panoramic roof': 28,
    'Parking assistant': 34,
    'Passengers airbag': 26,
    'Power steering': 28,
    'Rain sensor': 50,
    'Rear parking sensors': 67,
    'Rear side airbags': 50,
    'Rear view camera': 64,
    'Roof rails': 51,
    'SD socket': 49,
    'Shift paddles': 37,
    'Speed limiter': 47,
    'Start-Stop system': 53,
    'Sunroof': 32,
    'TV tuner': 0,
    'Tinted windows': 79,
    'Twilight sensor': 51,
    'USB socket': 60,
    'Velor upholstery': 75,
    'Xenon lights': 70}