name: Black Code Formatter Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  black-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # Specify your desired Python version

      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run Black Check
        run: |
          echo "Checking code formatting with Black..."
          black --check --line-length 100 .

      - name: Run Black and Apply Changes
        if: failure() # Only runs if the previous step (check) fails
        run: |
          echo "Formatting code with Black..."
          black .

      - name: Commit and Push Changes
        if: ${{ github.event_name == 'push' && failure() }} # Only commits if changes were made on push events
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Style: Format code using Black"
          git push origin HEAD:${{ github.ref_name }}
